In [1]:
import numpy as np 
import pandas as pd
import xgboost as xgb

In [4]:
df = pd.read_parquet("/Users/narendrafuloria/Desktop/Oil and Gas projects/oil_and_gas_anomaly_detection/data/raw/2.0.0/0 Normal Operation/WELL-00008_20170819060246.parquet")
df.head()

,ABER-CKGL,ABER-CKP,ESTADO-DHSV,ESTADO-M1,ESTADO-M2,ESTADO-PXO,ESTADO-SDV-GL,ESTADO-SDV-P,ESTADO-W1,ESTADO-W2,...,PT-P,P-TPT,QBS,QGL,T-JUS-CKP,T-MON-CKP,T-PDG,T-TPT,class,state
timestamp,,,,,,,,,,,,,,,,,,,,,
2017-08-19 06:02:46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
2017-08-19 06:02:47,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
2017-08-19 06:02:48,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
2017-08-19 06:02:49,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>
2017-08-19 06:02:50,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,<NA>,<NA>

In [5]:
df.describe()

,ABER-CKGL,ABER-CKP,ESTADO-DHSV,ESTADO-M1,ESTADO-M2,ESTADO-PXO,ESTADO-SDV-GL,ESTADO-SDV-P,ESTADO-W1,ESTADO-W2,...,PT-P,P-TPT,QBS,QGL,T-JUS-CKP,T-MON-CKP,T-PDG,T-TPT,class,state
count,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17644.0,17644.0
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 21244 entries, 2017-08-19 06:02:46 to 2017-08-19 11:56:49
Data columns (total 29 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   ABER-CKGL      0 non-null      float64
 1   ABER-CKP       0 non-null      float64
 2   ESTADO-DHSV    0 non-null      float64
 3   ESTADO-M1      0 non-null      float64
 4   ESTADO-M2      0 non-null      float64
 5   ESTADO-PXO     0 non-null      float64
 6   ESTADO-SDV-GL  0 non-null      float64
 7   ESTADO-SDV-P   0 non-null      float64
 8   ESTADO-W1      0 non-null      float64
 9   ESTADO-W2      0 non-null      float64
 10  ESTADO-XO      0 non-null      float64
 11  P-ANULAR       0 non-null      float64
 12  P-JUS-BS       0 non-null      float64
 13  P-JUS-CKGL     21244 non-null  float64
 14  P-JUS-CKP      0 non-null      float64
 15  P-MON-CKGL     0 non-null      float64
 16  P-MON-CKP      0 non-null      float64
 17  P-MON-SDV-P    0 non-null      float64
 18  P-PDG          0 non-null      float64
 19  PT-P           0 non-null      float64
 20  P-TPT          0 non-null      float64
 21  QBS            0 non-null      float64
 22  QGL            0 non-null      float64
 23  T-JUS-CKP      0 non-null      float64
 24  T-MON-CKP      0 non-null      float64
 25  T-PDG          0 non-null      float64
 26  T-TPT          0 non-null      float64
 27  class          17644 non-null  Int16
 28  state          17644 non-null  Int16
dtypes: Int16(2), float64(27)
memory usage: 4.7 MB